gene_list_f : "/home/jpeter/Scripts/SeedUTails/all_repr_genes.txt"
sample_list_f : "/home/jpeter/Scripts/SeedUTails/all_samples.txt"
repr_gene_model_f : "/home/jpeter/DATA/ReferenceGenomes/Athaliana/TAIR10/exon_intron_pos.repr.bed"
tail_result_f : "/home/jpeter/DATA/FLEPseq/Analysis/GS_F_df_tot.tsv.gz"
annot_file : "/home/jpeter/DATA/ReferenceGenomes/Athaliana/TAIR10/TAIR10_GFF3_genes_transposons.gff"
nb_bin_UTR : 20
nb_bin_CDS : 100
outplot : "/home/jpeter/DATA/FLEPseq/Analysis/Meta_all_genes_all_samples.pdf"
